services:
  caddy:
    image: caddy:2.7.8
    container_name: caddy
    networks:
      - appnet
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

  api:
    image: ${DOCKER_USERNAME}/app:latest
    container_name: api
    command: node dist/index.js
    volumes:
      - uploads_data:/app/uploads
    networks:
      - appnet
    env_file:
      - .env
    depends_on:
      - redis
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      retries: 5
    expose: 
      - "5000"

  worker:
    image: ${DOCKER_USERNAME}/app:latest
    command: node dist/worker.js
    env_file:
      - .env
    depends_on:
      - redis
    restart: on-failure

  events:
    image: ${DOCKER_USERNAME}/app:latest
    command: node dist/events.js
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
  caddy_data:
  caddy_config:
  uploads_data:

networks:
  appnet:
    driver: bridge