services:
  caddy:
    image: caddy:alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

    depends_on:
      - api
    restart: unless-stopped
    networks:
      - web
    environment:
      - TZ=Europe/Berlin

  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    networks:
      - web

  api:
    image: ${DOCKER_USERNAME}/app:latest
    container_name: api
    command: node dist/index.js
    volumes:
      - uploads_data:/app/uploads
    expose:
      - "5000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      retries: 5
    networks:
      - web

  worker:
    image: ${DOCKER_USERNAME}/app:latest
    command: node dist/worker.js
    env_file:
      - .env
    depends_on:
      - redis
    restart: on-failure
    networks:
      - web

  events:
    image: ${DOCKER_USERNAME}/app:latest
    command: node dist/events.js
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - web

volumes:
  redis_data:
  caddy_data:
  caddy_config:
  uploads_data:

networks: 
  web:
    driver: bridge