name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/app:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: "22"
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            set -e

            mkdir -p /opt/app
            cd /opt/app

            printf "%s\n" \
            "MONGO_URI=${{secrets.MONGO_URI}}" \
            "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" \
            "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" \
            "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_SECRET }}" \
            "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" \
            "PAYSTACK_URI=https://api.paystack.co" \
            "PAYSTACK_SECRET_KEY=${{ secrets.PAYSTACK_SECRET_KEY }}" \
            "PAYSTACK_PUBLIC_KEY=${{ secrets.PAYSTACK_PUBLIC_KEY }}" \
            "MOODLE_TOKEN=${{ secrets.MOODLE_TOKEN }}" \
            "MOODLE_URL=https://study.northbridgec.ca" \
            "EMAIL_HOST=${{ secrets.EMAIL_HOST }}" \
            "EMAIL_USER=${{ secrets.EMAIL_USER }}" \
            "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" \
            "CONTACT=\"Northbridge Collegiate <contact@northbridgec.ca>\"" \
            "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" \
            "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" \
            "REDIS_HOST=redis" \
            "REDIS_PORT=6379" \
            "FRONTEND_URL=https://northbridgec.ca" \
            "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" \
            "PORT=5000" \
            > .env

            curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -o docker-compose.yml \
              https://raw.githubusercontent.com/${{ github.repository }}/refs/heads/main/docker-compose.yml

            
            echo "DOCKER_USERNAME=$DOCKER_USERNAME"
            cat /opt/app/.env

            docker compose --env-file .env pull
            docker compose --env-file .env up -d

            docker image prune -af --filter "dangling=true"